version: '2'
services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/prometheus_db:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    links: 
      - prometheus:prometheus
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel, grafana-simple-json-datasource
      GF_SECURITY_ADMIN_PASSWORD: 123456
      GF_SECURITY_ADMIN_USER: admin
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
     - '9093:9093'
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/alertmanager-data:/data
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # Add if you are running on Mac
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
  
  nginx:
    image: nginx:stable-alpine

    volumes:
      - ./www/:/var/www/html
    #expose:
    #  - 80
    ports:
      - "80:80"