global: 
  external_labels: 
    monitor: devops_monitor
  scrape_interval: 5s

rule_files:
 - rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs: 

  - job_name: prometheus
    static_configs: 
      - targets: 
        - "prometheus:9090"
    basic_auth:
      username: admin
      password: 123456
        
  - job_name: node_exporter
    static_configs:
      - targets:
        - "node_exporter:9100"

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']